//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrivalTime
    {
        public int idArrivalTime { get; set; }
        public int idChild { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan arrivalTime1 { get; set; }
        public virtual children children { get; set; }
    }
}
