//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class children
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public children()
        {
            this.arrivalTimes = new HashSet<arrivalTime>();
        }
        public int IdChild { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string @class { get; set; }
        public int idParent1 { get; set; }
        public int idParent2 { get; set; }
        public int idInstitution { get; set; }
        public string tzChaild { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arrivalTime> arrivalTimes { get; set; }
        public virtual parent parent { get; set; }
        public virtual lnstitution lnstitution { get; set; }
        public virtual parent parent1 { get; set; }
    }
}
