//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class facialDBEntities : DbContext
    {
        public facialDBEntities()
            : base("name=facialDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arrivalTime> arrivalTimes { get; set; }
        public virtual DbSet<children> childrens { get; set; }
        public virtual DbSet<lnstitution> lnstitutions { get; set; }
        public virtual DbSet<parent> parents { get; set; }
    }
}
